var songs = {
  questOfTheManwhore: [
    // Quest of the Manwhore
    /Gaze into my choco?late eyes?/i,
    'Let my music sterilise',
    /Let my music ster[ai]li[sz]e/i,
    'Give to me your hard earned coin',
    /Give to me your hard earned coin/i,
    'I\'ll share with you my tortured groin',
    /I\'?ll? share with you my tortured groin/i,
    'What you\'re feeling is not weird',
    /What you(?:\'?re?| are) feeling is not w(?:ei|ie)rd/i,
    'You want to burrow in my beard',
    /You want to b[uo]rrow in my beard/i,
    'Gaze upon my chiselled abs',
    /Gaze upon my chisell?ed abs/i,
    'I no longer have the crabs',
    /I no longer have the crabs/i,
    'My rhymes will grab you by the throat',
    /My rh?[iy]me?s will grab you by the throat/i,
    'And ride you like a sturdy goat',
    /And ride you like a sturdy goat/i,
    'I will drown you in my scent',
    /I will drown you in my scent/i,
    'with or without your consent',
    /with or with[ \-]?out your consent/i,
    'I am a whore of some renown',
    /I am a whore of some rek?nown/i,
    'Your buttocks are my hunting ground',
    /Your buttocks are my hunting ground/i,
    'I am a manwhore without peer',
    /I am a man[ \-]?whore without peer/i,
    'Absorbing sex from the atmosphere',
    /(?:bsorbing|sucking) sex from the atmosphere/i,
    'Pressure building like a cyst',
    /Prea?ss?ure building like a c[yi]st/i,
    'I want to share with you love\'s fist',
    /I want to share with you love\'?s fist/i,
    'I\'ll lick your feet, I\'ll wear a collar',
    /I\'?ll? lick your feet\,? I\'?ll? wear a collar/i,
    'I\'ll do anything for a dollar',
    /I\'?ll? do anything for a dollar/i,
    'I will fit you like a glove',
    /I will fit you like a glove/i,
    'More precious than a father\'s love',
    /More prea?ciou?s than a father\'?s love/i,
    'not that i would really know',
    /not that i would really know/i,
    'I like my women rich and young',
    /I like my women rich and young/i,
    'The kiss of yoghurt on my tongue',
    /The kiss of you?gh?urt on my tongue/i,
    'I wield a fleshy latin sword',
    /I [wy]ield a fleshy latin sword/i,
    'Raptor jesus is my lord',
    /Raptor jesus is my lord/i,
    'Let me be your phantom limb',
    /Let me be your phantom limb/i,
    'Crack and yoghurt keeps me slim',
    /Crack and you?gh?urt keeps? me slim/i,
    'Struggling with modernity',
    /Strugg?ll?ing with modernity/i,
    'A whore for all eternity.'
  ],
  
  danceOfTheManwhore: [
    //Dance of the Manwhore
    /Love as large as bront[oa]sa[uo]r[uo]s/i,
    'Passion like a bleeding walrus',
    /Passion like a bleeding walrus/i,
    'Our love is real it\'s no mirage',
    /Our love is real it(?:\'?s| is) no mirage/i,
    'Want to lock you in my garage',
    /(?:I )?Want to lock you in my garage/i,
    'Climb upon my trusty steed',
    /Climb (?:u|a)pon my trusty steed/i,
    'Later you will taste my seed',
    /Later you will taste my seed/i,
    'This heart of mine is yours to capture',
    /Th(?:is|e) heart of mine is yours to capture/i,
    'From now on til Velocirapture',
    /From now on till? Velocirapt(?:ure|or)/i,
    'Wield my passion like an axe',
    /[WY]ield my passion like an axe/i,
    'It\'s warm and gooey just like wax',
    /It(?:\'?s| is) warm and gooey\,? just like wax/i,
    'You cannot tame such juicy lust',
    /You can(?: ?not|\'?nt) tame such juicy lust/i,
    'Can you withstand my manly musk',
    /Can you withstand my manly musk/i,
    'Roses are red violets are blue',
    /Roses are red\,? violets are blue/i,
    'I must eat yoghurt of off you',
    /I must eat you?gh?urt off? off? you/i,
    'Know that I can never hold back',
    /Know that I can(?: never| not|\'?t) hold back/i,
    'That might be why I smoke the crack',
    'My father never loved me...',
    /That (?:might|may) be why I smoke the crack/i,
    'My father never loved me...',
    /'My father never loved me/i,
    'Love is like a ripened squid',
    /Love is like a ripened squid/i,
    'It stinks with limp appendages',
    /It (?:stinks|re[ea]ks) with limp app?end[ae]ges/i,
    'You scratch the rash that\'s on my ass',
    /(?:You )?scratch the rash that(?:\'?s| is) on my ass/i,
    'The itch only love can surpass',
    /The itch only love can surpass/i,
    'Yoghurt\'s a dish best served chilled',
    /You?gh?urt(?:\'?s| is) a dish best served chill(?:ed)?/i,
    'Forgot to get my prescription filled',
    /Forg[oe]t to get my p(?:re|er)scription fill(?:ed)?/i,
    'Tonight I will have sex with you',
    /Tonight I(?: will|\'?ll?) have sex with you/i,
    'Then we will prepare a stew',
    /Then (?:we|i)(?: will|\'ll?) prepare a stew/i,
    'Just lie down and let me touch',
    /Just lie down and let me touch/i,
    'I promise you it won\'t hurt much',
    /I promise you\,? it won\'?t hurt much/i,
    'Stalk like a lizard of the night',
    /Stalk like a lizard of the night/i,
    'Come closer, Fernando won\'t bite',
    /Come closer\,? Fernando won\'?t bite/i,
    'Tears and screams of pain and pleasure',
    /Tears and screams of pain and pleasure/i,
    'Our gifts we will share forever',
    /(?:Our |The )?gifts we(?: will|\'?ll?) share forever/i,
    /We(?: will|\'?ll?) share our gifts forever/i,
    'Drenched deep in sweaty brine',
    /Drenched deep in sweaty brine/i,
    'Is this blood yours or mine\?'
  ],
  
  stillAlive: [
    /this was a triumph/i,
    'I\'m making a note here: HUGE SUCCESS',
    /i(?:\'?m| am) making a note here.*huge success/i,
    'It\'s hard to overstate my satisfaction',
    /i(?:\'?m| am) making a note here/i,
    'HUGE SUCCESS',
    /it(?:\'?s| is) ha+rd to over[ \-]?state my satisfaction/i,
    'Aperture Science',
    /Ap[ae]r[ae]?ture? science/i,
    'We do what we must because we can',
    /we do what we must.? because we can/i,
    'For the good of all of us',
    /we do what we must/i,
    'Because we can',
    /because we can/i,
    'For the good of all of us',
    /for the good of all of us/i,
    'Except the ones who are dead',
    /exc?ept the ones who are dead/i,
    'But there\'s no sense crying over every mistake',
    /but there(?:\'?s| is) no sense crying over every mistake/i,
    'You just keep on trying till you run out of cake',
    /(?:you |lets )?just keep on trying (?:un)?till? (?:you|we) run out of cake/i,
    'And the science gets done',
    /and the science (?:gets|is) done/i,
    'And you make a neat gun',
    /and you (?:make|get) a (?:neat|cool) gun/i,
    'For the people who are still alive',
    /for the people who are still alive/i,
    'I\'m not even angry',
    /i(?:\'?m| am) not even angry/i,
    'I\'m being so sincere right now',
    /i(?:\'?m| am) (?:being )?(?:so |very )? sincere right now/i,
    'Even though you broke my heart and killed me',
    /even though you (?:broke|tore) my heart.*and killed me/i,
    'And tore me to pieces',
    /even though you (?:broke|tore)/i,
    'and killed me',
    /and killed me/,
    'And tore me to pieces',
    /and tore me to pieces/i,
    'And threw every piece into a fire',
    /and threw every piece.*into a fire/i,
    'As they burned it hurt because I was so happy for you!',
    /and threw every piece/i,
    'Into a fire',
    /into a fire/,
    'As they burned it hurt because I was so happy for you!',
    /(?:but )?as they burned it hurt.? because.? I (?:was|am) so happy for you/i,
    'Now these points of data make a beautiful line',
    /(?:but )?as they burned it hurt because/i,
    'I was so happy for you!',
    /I (?:was|am) so happy for you/i,
    'Now these points of data make a beautiful line',
    /now these points? of data make a beautifull? line/i,
    'And we\'re out of beta, we\'re releasing on time',
    /and we(?:\'?re?| are) (?:out of|finished) beta.*we(?:\'re?| are) releasing on time/i,
    'So I\'m GLaD. I got burned',
    /and we(?:\'?re?| are) (?:out of|finished) beta/i,
    'We\'re releasing on time',
    /we(?:\'?re?| are) releasing on time/i,
    'So I\'m GLaD. I got burned',
    /so i(?:\'?m| am) glad.? i got burned/i,
    'Think of all the things we learned',
    /(?:think of|look at) all the things we learned/i,
    'For the people who are still alive',
    /for the people who are.*still alive/i,
    'Go ahead and leave me',
    /for the people who are/i,
    'Still alive',
    /still alive/i,
    'Go ahead and leave me',
    /go (?:ahead|out)? and leave me/i,
    'I think I prefer to stay inside',
    /I think I prefer to stay inside/i,
    'Maybe you\'ll find someone else to help you',
    /maybe you(?:\'?ll?| will) find someone else to help you/i,
    'Maybe Black Mesa',
    /maybe you(?:\'?ll?| will) find someone else/i,
    'To help you',
    /to help you/i,
    'Maybe Black Mesa',
    /maybe black mesa/i,
    'THAT WAS A JOKE. HAHA. FAT CHANCE',
    /that was a joke.*ha ?ha.*fat chance/i,
    'Anyway, this cake is great',
    /that was a joke.*ha ?ha/i,
    'FAT CHANCE',
    /that was a joke/i,
    'HAHA. FAT CHANCE',
    /ha ?ha.*fat chance/i,
    'Anyway, this cake is great',
    /fat chance/i,
    'Anyway, this cake is great',
    /Anyways?.? this cake is great/i,
    'It\'s so delicious and moist',
    /it(?:\'?s| is) so dell?iciou?s and moist/i,
    'Look at me still talking when there\'s science to do',
    /look at me still talking.? when there(?:\'?s| is) science to do/i,
    'When I look out there, it makes me GLaD I\'m not you',
    /look at me still talking/i,
    'When there\'s science to do',
    /when there(?:\'?s| is) science to do/i,
    'When I look out there, it makes me GLaD I\'m not you',
    /when I look out there.? it makes me glad i\'?m not you/i,
    'I\'ve experiments to run',
    /when I look out there/i,
    'It makes me GLaD I\'m not you',
    /it makes me glad i\'?m not you/i,
    'I\'ve experiments to run',
    /i(?:\'?ve| have) experiments to run/i,
    'There is research to be done',
    /there(?:\'?s| is) research to be done/i,
    'On the people who are still alive',
    /on the people who are.? still alive/i,
    'And believe me I am still alive',
    /on the people who are/i,
    'Still alive',
    /still alive/i,
    'And believe me I am still alive',
    /and believe me I am.? still alive/i,
    'I\'m doing science and I\'m still alive',
    /and believe me I am/i,
    'Still alive',
    /still alive/i,
    'I\'m doing science and I\'m still alive',
    /I(?:\'?m| am) doing science and I\'?m.? still alive/i,
    'I feel FANTASTIC and I\'m still alive',
    /I(?:\'?m| am) doing science and I\'?m/i,
    'Still alive',
    /still alive/i,
    'I feel FANTASTIC and I\'m still alive',
    /I feel fantastic and i\'?m.? still alive/i,
    'While you\'re dying I\'ll be still alive',
    /I feel fantastic and i\'?m/i,
    'Still alive',
    /still alive/i,
    'While you\'re dying I\'ll be still alive',
    /(?:while|when) you(?:\'?re?| are|\'?ll? be| will be) d(?:y|ie)ing i(?:\'?ll?| will) be.? still alive/i,
    'And when you\'re dead I will be still alive',
    /(?:while|when) you(?:\'?re?| are|\'?ll? be| will be) d(?:y|ie)ing i(?:\'?ll?| will) be/i,
    'still alive',
    /still alive/i,
    'And when you\'re dead I will be still alive',
    /(?:and )?when you(?:\'?re?| are|\'?ll? be| will be) dead i(?:\'?ll?| will) be.? still alive/i,
    'still alive',
    /(?:and )?when you(?:\'?re?| are|\'?ll? be| will be) dead i(?:\'?ll?| will) be/i,
    'still alive',
    /still alive/i,
    'STILL ALIVE'
  ],
  
  wantYouGone: [
    /Well here we are again/i,
    'it\'s always such a pleasure',
    /it\'s always such a pleasure/i,
    'Remember when you tried to kill me twice?',
    /Remember when you tried to kill me twice\?/i,
    'Oh how we laughed and laughed',
    /Oh how we laughed and laughed/i,
    'Except I wasn\'t laughing',
    /Except I wasn\'t laughing/i,
    'Under the circumstances I\'ve been shockingly nice',
    /Under the circumstances I\'ve been shockingly nice/i,
    'You want your freedom? Take it',
    /You want your freedom\? Take it/i,
    'That\'s what I\'m counting on',
    /That\'s what I\'m counting on/i,
    'I used to want you dead',
    /I used to want you dead/i,
    'But now i only want you gone',
    /But now I only want you gone/i,
    'She was a lot like you',
    /She was a lot like you/i,
    '(Maybe not quite as heavy)',
    /\(Maybe not quite as heavy\)/i,
    'Now little Caroline is in here too',
    /Now little Caroline is in here too/i,
    'One day they woke me up',
    /One day they woke me up/i,
    'So I could live forever',
    /So I could live forever/i,
    'It\'s such a shame the same',
    /It\'s such a shame the same/i,
    'Will never happen to you',
    /Will never happen to you/i,
    'You\'ve got your short sad life left',
    /You\'ve got your short sad life left/i,
    'That\'s what I\'m counting on',
    /That\'s what I\'m counting on/i,
    'I\'ll let you get right to it',
    /I\'ll let you get right to it/i,
    'Now I only want you gone',
    /Now I only want you gone/i,
    'Goodbye my only friend',
    /Goodbye my only friend/i,
    'Oh, did you think I meant you?',
    /Oh, did you think I meant you\?/,
    'That would be funny if it weren\'t so sad',
    /That would be funny if it weren\'t so sad/i,
    'Well you have been replaced',
    /Well you have been replaced/i,
    'I don\'t need anyone now',
    /I don\'t need anyone now/i,
    'When I delete you maybe, I\'ll stop feeling so bad',
    /'When I delete you maybe, I\'ll stop feeling so bad'/i,
    'Go make some new disaster',
    /Go make some new disaster/i,
    'That\'s what I\'m counting on',
    /That's what I\'m counting on/i,
    'You\'re someone else\'s problem',
    /You\'re someone else\'s problem/i,
    'Now I only want you gone',
    /Now I only want you gone/i,
    'Now i only want you...',
    /Now i only want you.../i,
    'gone'
  ]
};

function checkLines(songName, fromLine, toLine) {
  var song = songs[songName];
  var handled = false;
  for (var i = fromLine; i < toLine; i += 1)
    if (typeof song[i] != 'string')
      if (song[i].test(message.content))
        for (i = i + 1; i < song.length; i += 1) {
          if (typeof song[i] != 'string') {
            if (!handled)
              continue;
            else
              return i;
          }
          
          say(song[i], true);
          handled = true;
          if (i == song.length - 1)
            return 0;
        }
  return -1;
}

var now = new Date().getTime();
var songNames = Object.keys(songs);
for (var i = 0; i < songNames.length; i += 1) {
  var song = songs[songNames[i]];
  
  if (typeof storage[songNames[i]] !== 'object')
    storage[songNames[i]] = { progress: 0, lastLineTime: 0 };
  if (now > storage[songNames[i]].lastLineTime + 60000)
    storage[songNames[i]].progress = 0;
  var progress = storage[songNames[i]].progress;
  
  var nextProgress = checkLines(songNames[i], progress, song.length);
  if (nextProgress == -1)
    nextProgress = checkLines(songNames[i], 0, progress);
  
  if (nextProgress != -1) {
    storage[songNames[i]].progress = nextProgress;
    storage[songNames[i]].lastLineTime = now;
    save();
    setHandled(true);
    
    i = songNames.length;
    break;
  }
}
